source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

gem 'activeadmin'
gem 'argon2' # used by JWT
gem 'bcrypt' # used by clearance
gem 'clearance' # pwd management -- https://github.com/thoughtbot/clearance/
gem 'foreman'
gem 'faraday-retry' # Octokit uses for automated retries for failures
gem 'httparty'
gem 'jsbundling-rails', '~> 1.1'
gem 'jwt'
gem 'octokit'
gem 'pg', '~> 1.1' # Use postgresql as the database for Active Record
gem 'puma', '~> 5.0' # Use the Puma web server [https://github.com/puma/puma]
gem 'rack-cors'
gem 'rails', '~> 7.0.4'
gem 'rodash'              # used by lexicon.rb -- lodash-style .get()
gem 'sass-rails', '~> 5.0'
gem 'sendgrid-actionmailer'       # https://github.com/eddiezane/sendgrid-actionmailer
gem 'sendgrid-ruby'               # SendGrid's official api gem -- https://github.com/sendgrid/sendgrid-ruby

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem 'spring'
end


