# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks


# Replace yarn with npm
# from https://dmitryshvetsov.com/how-to-use-webpacker-with-npm-instead-of-yarn-rails-guide
Rake::Task['yarn:install'].clear if Rake::Task.task_defined?('yarn:install')
Rake::Task['javascript:build'].clear if Rake::Task.task_defined?('javascript:build')
namespace :javascript do
  desc "Build your JavaScript bundle"
  task :build do
    puts "-- Lexicon Rakefile: running javascript:build --"
    unless system "npm install && npm run build"
      raise "Lexicon Rakefile: Command javascript:build failed, ensure npm is installed and `npm run build` runs without errors"
    end
  end
end

Rake::Task['css:build'].clear if Rake::Task.task_defined?('css:build')
# namespace :css do
#   desc "Build your CSS bundle"
#   task :build do
#     puts "-- Lexicon Rakefile: running css:build --"
#     unless system "npm install && npm run build:css"
#       raise "Lexicon Rakefile: Command css:build failed, ensure npm is installed and `npm run build:css` runs without errors or use SKIP_CSS_BUILD env variable"
#     end
#   end
# end

